### ISSUE TITLE
Unexpected client exception regarding null fields

### ISSUE THREAD

**Issue by cavallium** [Telegram4J/Telegram4J#13]
```java
2022-05-07 01:04:05.449 ERROR 4175655 DefaultMTProtoClient : [C:0x1cfa7350] Unexpected client exception
java.lang.NullPointerException: Cannot read field "method" because "request" is null
        at telegram4j.mtproto.RpcException.create(RpcException.java:52)
        at telegram4j.mtproto.DefaultMTProtoClient.handleServiceMessage(DefaultMTProtoClient.java:750)
        at telegram4j.mtproto.DefaultMTProtoClient.lambda$handleServiceMessage$51(DefaultMTProtoClient.java:770)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:386)
        at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:272)
        at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:230)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by skykatik** [comment]
Added handling for this case in Telegram4J@3248b07, but it does not fix the problem itself. Can you enable `DEBUG` level for 
`telegram4j.mtproto.rpc` logger in your configuration and send logs with this error?

**Comment by cavallium** [comment]
here is the log: https://local.cavallium.it/mirrors/latest.txt
